# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demp < Formula
  desc "A CLI tool for doing X, Y, and Z."
  homepage "https://github.com/rianfowler/demp"
  version "0.1.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rianfowler/demp/releases/download/v0.1.15/demp_0.1.15_darwin_amd64.tar.gz"
      sha256 "83e7b8e73262f1768839c4ec7a7fc154c46b9e2fc6da0de55969b455a630565c"

      def install
        bin.install "demp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rianfowler/demp/releases/download/v0.1.15/demp_0.1.15_darwin_arm64.tar.gz"
      sha256 "056c2f4c684a360745c7e945a1574a3151056b6931c98e91ebb4d03266e31f9d"

      def install
        bin.install "demp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rianfowler/demp/releases/download/v0.1.15/demp_0.1.15_linux_amd64.tar.gz"
        sha256 "ea3f2911c3ad5a1516c6cc547724645e511fcd4ad7bdfcded7c78622a53981da"

        def install
          bin.install "demp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rianfowler/demp/releases/download/v0.1.15/demp_0.1.15_linux_arm64.tar.gz"
        sha256 "b9e6a18dd425aa47df9352d309a429e082c9cfb168691eb9cdd84dfc3eeb2b9d"

        def install
          bin.install "demp"
        end
      end
    end
  end

  test do
    system "#{bin}/demp", "--help"
  end
end
