# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demp < Formula
  desc "A CLI tool for doing X, Y, and Z."
  homepage "https://github.com/rianfowler/demp"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rianfowler/demp/releases/download/v0.1.6/demp_0.1.6_darwin_amd64.tar.gz"
      sha256 "77c6ee9e468139afc6b1be0de8ba0e9e56acc860cabb42cb52ae98b5de480aec"

      def install
        bin.install "demp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rianfowler/demp/releases/download/v0.1.6/demp_0.1.6_darwin_arm64.tar.gz"
      sha256 "079197e744cd2033640b12faaf90233de550205aaa68638a697c4fe491e5fd2f"

      def install
        bin.install "demp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rianfowler/demp/releases/download/v0.1.6/demp_0.1.6_linux_amd64.tar.gz"
        sha256 "695d0288c44bf1666619ef4dfd71d65632c33ee3c094ee8ad2f4d4abc8c84b25"

        def install
          bin.install "demp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rianfowler/demp/releases/download/v0.1.6/demp_0.1.6_linux_arm64.tar.gz"
        sha256 "6b498d0020a1c6ac608f2e6cf79ab1cbc5371d4723a83b3a82c2ce3b4c3654ac"

        def install
          bin.install "demp"
        end
      end
    end
  end

  test do
    system "#{bin}/demp", "--help"
  end
end
