# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demp < Formula
  desc "A CLI tool for doing X, Y, and Z."
  homepage "https://github.com/rianfowler/demp"
  version "0.1.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rianfowler/demp/releases/download/v0.1.15/demp_0.1.15_darwin_amd64.tar.gz"
      sha256 "90fecc2348834ca13358795e9407c26800313e49a80473b4efcb23667cedac23"

      def install
        bin.install "demp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rianfowler/demp/releases/download/v0.1.15/demp_0.1.15_darwin_arm64.tar.gz"
      sha256 "d7a39b54ad43e4c01aeff9eb43d9afa0f5a8f9f4d2c1377d73fd1e2ff6b457ea"

      def install
        bin.install "demp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rianfowler/demp/releases/download/v0.1.15/demp_0.1.15_linux_amd64.tar.gz"
        sha256 "b2c797aebab32db1fdc6f48122b471c7dffc90c5ce7639db33f17b65be01266d"

        def install
          bin.install "demp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rianfowler/demp/releases/download/v0.1.15/demp_0.1.15_linux_arm64.tar.gz"
        sha256 "018b3a5ac5b119717212da5b6325e68d28ecfb9acdacc1a4212b08e1af5c6fae"

        def install
          bin.install "demp"
        end
      end
    end
  end

  test do
    system "#{bin}/demp", "--help"
  end
end
