# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ri < Formula
  desc "A CLI tool for doing X, Y, and Z."
  homepage "https://github.com/rianfowler/ri"
  version "0.0.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rianfowler/ri/releases/download/v0.0.23/ri_0.0.23_darwin_amd64.tar.gz"
      sha256 "6060d680bf2e3ecee5a6b36b17f76ccef4c8072fe352fba299c91ce5f0bcb71d"

      def install
        bin.install "ri"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rianfowler/ri/releases/download/v0.0.23/ri_0.0.23_darwin_arm64.tar.gz"
      sha256 "187e14737e681759a9f07a0d4d3a44065ac5155f855b402d53cc627a63b5b380"

      def install
        bin.install "ri"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rianfowler/ri/releases/download/v0.0.23/ri_0.0.23_linux_amd64.tar.gz"
        sha256 "43a2cd815c790fbc72bdacb46d83794caa830d8bde692c42e1da9be95694f85a"

        def install
          bin.install "ri"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rianfowler/ri/releases/download/v0.0.23/ri_0.0.23_linux_arm64.tar.gz"
        sha256 "8784e8019843eb72e250abc265c49fe57120c6a2506d8e3fd0061c2802645bf3"

        def install
          bin.install "ri"
        end
      end
    end
  end

  test do
    system "#{bin}/ri", "--help"
  end
end
